@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Network Administrator" as ADM
participant ":CreateStoreUI" as UI
participant ":CreateStoreController" as CTRL
participant "storeMapper"
participant "Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "StoreRepository:\nStoreRepository" as storeRepository
participant "Store\n:Store" as store

activate ADM

        ADM -> UI : asks to create a new store

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create



        UI --> ADM : requests data
    deactivate UI

    ADM -> UI : types requested data (Codigo,\nHoraAbertura,\nHoraEncerramento)
    activate UI


    activate UI

        UI -> CTRL : createStore(Codigo,\nHoraAbertura,\nHoraEncerramento)
        activate CTRL


        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton -> CTRL : repositories
        deactivate RepositorySingleton



        CTRL -> PLAT : getStoreRepositories()
        activate PLAT

        PLAT -> CTRL : StoreRepository
        deactivate PLAT








            |||
            CTRL -> storeRepository: createStore(Codigo,\nHoraAbertura,\nHoraEncerramento)
            activate storeRepository

                storeRepository -> store**: create(Codigo,\nHoraAbertura,\nHoraEncerramento)
                storeRepository -> storeRepository: addStore (Store)

                storeRepository -> storeRepository: validateStore(Store)


                storeRepository --> CTRL : store

            deactivate storeRepository

            CTRL -> storeMapper : ToDTO(Store)

            activate storeMapper

                storeMapper -> PLAT : getStore()

                activate PLAT

                    PLAT --> storeMapper : StoreRepository

                deactivate PLAT

                storeMapper -> storeMapper : toDTO()

                storeMapper --> CTRL : StoreDTO

            deactivate storeMapper

            CTRL --> UI: StoreDTO
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml