@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor Manager
participant ":CreateAgentUI" as UI
participant ":CreateAgentController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "storeListRepository:\nStoreListRepository" as StoreListRepository

participant "currentSession\n:UserSession" as SESSAO
participant "organization\n:Organization" as ORG
participant "agent\n:Agent" as AGENT

activate Manager

        Manager -> UI : asks to create a new task

        activate UI

'            UI --> Manager : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getTaskCategories()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getStoreListRepository()
                activate PLAT

                    PLAT --> CTRL: storeListRepository
                deactivate PLAT

                CTRL -> StoreListRepository : getTaskCategories()
                activate StoreListRepository

                    StoreListRepository --> CTRL : taskCategoryList
                deactivate StoreListRepository

                CTRL --> UI : taskCategoryList
            deactivate CTRL

            UI --> Manager : shows store list\n and asks to select one
        deactivate UI

    Manager -> UI : selects a store
    activate UI

        UI --> Manager : requests data
    deactivate UI

    Manager -> UI : types requested data (reference, description, \ninformal description, technical description,\nduration, cost)
    activate UI

        UI --> Manager : shows selected category and requested data
    deactivate UI

    Manager -> UI : submits data
    activate UI

        UI -> CTRL : createAgent(reference,\ndescription,\ninformalDescription,\ntechnicalDescription,\nduration, cost,\nStoreName/code)
        activate CTRL

            CTRL -> CTRL : getStoreListRepository(Store/code)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getStoreListRepository()
                activate PLAT

                    PLAT -> CTRL : storeListRepository
                deactivate PLAT

                CTRL -> StoreListRepository : getStoreListRepository(Store/code))
                activate StoreListRepository

                    StoreListRepository --> CTRL : store
                deactivate StoreListRepository
                    CTRL --> CTRL : store
            deactivate CTRL

            |||
            CTRL -> CTRL : getAgent()
            activate CTRL


                CTRL -> SESSAO: email = getAgentEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT

                CTRL -> ORG: getEmployeeByEmail(email)
                activate ORG

                    ORG --> CTRL : employee
                deactivate ORG

                CTRL --> CTRL : employee
            deactivate CTRL

            |||
            CTRL -> ORG: createAgent(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, , taskCategory, employee)
            activate ORG

                ORG -> AGENT**: create(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, taskCategory, employee)
                ORG -> ORG: addAgent (agent)


                activate ORG
                    ORG -> ORG: validateAgent(agent)
                    activate ORG
                        ORG --> ORG
                    deactivate ORG

                    ORG --> ORG
                deactivate ORG

                ORG --> CTRL : Agent

            deactivate ORG

            CTRL --> UI: Agent
            deactivate CTRL
            UI --> Manager: displays operation success
    deactivate UI

deactivate Manager

@enduml