@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Store Manager" as Manager
participant ":CreateAgentUI" as UI
participant ":CreateAgentController" as CTRL
participant "Repositories" as RepositorySingleton
participant "StoreRepository:\nStoreRepository" as storeRepository
participant "AgentRepository:\nAgentRepository" as agentRepository
participant "Agent\n:Agent" as Agent
participant "AgentMapper" as mapper

activate Manager

        Manager -> UI : asks to create a new agent
        activate UI

        UI -> CTRL : getAvailableStores()
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton -> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> storeRepository : getAllStores()
        activate storeRepository

            storeRepository --> CTRL : List of Stores
        deactivate storeRepository

        CTRL --> UI : AvailableStoresDTO
    deactivate CTRL

    UI --> Manager : displays available stores

    Manager -> UI : selects a store
    activate UI

        UI -> CTRL : validateAndSubmit(Name,\nCitizen Card,\nEmail,\nPhone,\nSelected Store)
        activate CTRL

        CTRL -> agentRepository : createAgent(Name,\nCitizen Card,\nEmail,\nPhone,\nSelected Store)
        activate agentRepository

            agentRepository -> Agent : create(Name,\nCitizen Card,\nEmail,\nPhone,\nSelected Store)
            agentRepository -> agentRepository : addAgent(Agent)
            agentRepository --> CTRL : Agent
        deactivate agentRepository

        CTRL -> mapper : toDTO(Agent)
        activate mapper
            mapper --> CTRL : AgentDTO
        deactivate mapper

        CTRL --> UI : AgentDTO
    deactivate CTRL

    UI --> Manager : displays operation success
deactivate UI

deactivate Manager
@enduml
